name: Launch Modified Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  modified:
    runs-on: ubuntu-latest
    outputs:
      specs: ${{ steps.modified_files.outputs.test_paths }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine modified files
        id: modified_files
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          ADDED_MODIFIED_TESTS=$(git diff --name-status origin/$GITHUB_BASE_REF HEAD -- cypress/e2e | grep -E '^[AM]' | cut -f2)
          TESTS_PATHS=$(echo "$ADDED_MODIFIED_TESTS" | tr "\n" "," | sed 's/.$//')
          echo "test_paths=$TESTS_PATHS" >> $GITHUB_OUTPUT
          echo "$TESTS_PATHS"

  run-cypress:
    needs: modified
    uses: ./.github/workflows/reusable.yml
    with:
      spec-path: ${{needs.modified.outputs.specs}}
    secrets: inherit
